version: '3.9'

services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: .docker/server.dockerfile
    restart: always
    environment:
      TZ: Europe/Moscow
    ports:
      - 8080:4567
    links:
      - db
    command: ruby bin/server.rb -o 0.0.0.0
    tty: true
    stdin_open: true

  db:
    container_name: mysql
    build:
      context: .
      dockerfile: .docker/mysql.dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_servers_com
      TZ: Europe/Moscow
    ports:
      - 6603:3306
