version: '3.9'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080
    links:
      - server

  server:
    image: jarockiart/pingmeter_server:v.0.1
    container_name: server
    restart: always
    environment:
      TZ: Europe/Moscow
    ports:
      - 4567:4567
    links:
      - db
    command: ruby bin/server.rb -o 0.0.0.0
    tty: true
    stdin_open: true

  db:
    image: jarockiart/pingmeter_mysql:v.0.1
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_servers_com
      TZ: Europe/Moscow
    ports:
      - 6603:3306
